### ISSUE TITLE
Circulation kiosk not updating in a timely manner

### ISSUE THREAD

**Issue by likello** [osulp/Room-Reservation#241]
I'm not sure if it's because of a truncation setting or because the kiosk isn't getting the information quickly enough, but the kiosk (aside from the issue #240) isn't displaying the correct number of rooms available. For example, the kisok display says (12:24 PM) that there are no rooms available for at least an hour, but there are two available. The two rooms available (1812 and 5564) were truncated at 12:16 PM, but it's still not showing up. These reservations were truncated because the patron never picked up their key.

**Comment by revgum** [comment]
Available room count for the current kiosk software was evaluated and implemented during the release of that software, this ticket is no longer valid.
