### ISSUE TITLE
Room reservation link in the email notification message appears to be broken

### ISSUE THREAD

**Issue by luisgreg99** [osulp/Room-Reservation#285]
From Dan: "The 'log into the reservation system' link isn’t resolving to anything."

**Comment by feebeef** [comment]
The URL keeps getting changed to "../" I don't know why this is happening. This is the second time that the URL has been changed to ".../" I've tried changing to "rooms.library.oregonstate.edu/" and the change isn't sticking. I've tried clicking on the save button just below the text editor for just the cancellation and reservation email footer in addition to clicking on "Save" at the very bottom of the "Settings" page. Is this an issue that is from outdated Ruby?

**Comment by feebeef** [comment]
It seems that the editing or creation of hyperlinks is broken. In the meantime, I have deleted the broken links and listed the URL in plain text, so we don't have something broken.

**Comment by revgum** [comment]
N/A
