### ISSUE TITLE
Reserved rooms not displaying in room reservation area.

### ISSUE THREAD

**Issue by straleyb** [osulp/Room-Reservation#308]

**Comment by mellinma** [comment]
In other words, the blue indicator showing a logged in users current reservation is not functional

**Comment by mellinma** [comment]
![screen shot 2018-06-08 at 12 47 40 pm](https://user-images.githubusercontent.com/11778515/41177805-37ab0ef4-6b1a-11e8-9066-4d748e25a798.png)

In addition, along with the blue display indicator, the success message should also appear upon a successful reservation action
