### ISSUE TITLE
Reporter Reservation Pessimistic Locking

### ISSUE THREAD

**Issue by tpendragon** [osulp/Room-Reservation#41]
Circ would like it so that if a reporter/admin clicks a spot it immediately holds that start time + minimum(6 hours, time until next reservation) until they either make the reservation, click out of the box, or a time limit elapses (maybe 2 minutes? Configurable.)

**Comment by revgum** [comment]
Very old ticket, we'll reevaluate future needs and establish new tickets with what is found.
