### ISSUE TITLE
Make User an AR Model

### ISSUE THREAD

**Issue by tpendragon** [osulp/Room-Reservation#83]
Push this off until later, but I've been batting around the idea of making User a real AR model - making it an OpenStruct isn't really getting us anything besides headaches. We should just need to make attr_accessor for cases when the table doesn't exist for it to work, and it would allow us to pretty easily build a traditional sign up system for those who don't want to use CAS.

**Comment by revgum** [comment]
Old ticket, will evaluate if this is a need in a future system.. but for the meantime, there isn't a good argument to do this work in the application.
